import type { OpenAPIV3 } from "openapi-types";
import { describe, expect, it } from "vitest";
import { createOpenApiDocument } from "../scripts/openapi-document.js";

const HTTP_METHODS = [
  "get",
  "put",
  "post",
  "delete",
  "options",
  "head",
  "patch",
  "trace",
] as const;

function collectOperationIds(document: OpenAPIV3.Document): string[] {
  const operationIds: string[] = [];
  for (const pathItem of Object.values(document.paths)) {
    if (!pathItem) continue;
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (operation?.operationId) operationIds.push(operation.operationId);
    }
  }
  return operationIds;
}

describe("OpenAPI contract", () => {
  it("documents every implemented endpoint with a stable operation ID", async () => {
    const document = await createOpenApiDocument();
    expect(Object.keys(document.paths).sort()).toEqual([
      "/api/v1/admin/attributes",
      "/api/v1/admin/attributes/{id}",
      "/api/v1/admin/audit-events",
      "/api/v1/admin/categories",
      "/api/v1/admin/categories/{id}",
      "/api/v1/admin/content/article-categories",
      "/api/v1/admin/content/articles",
      "/api/v1/admin/content/articles/{id}",
      "/api/v1/admin/content/articles/{id}/archive",
      "/api/v1/admin/content/articles/{id}/duplicate",
      "/api/v1/admin/content/articles/{id}/publish",
      "/api/v1/admin/content/home",
      "/api/v1/admin/content/home/archive",
      "/api/v1/admin/content/home/publish",
      "/api/v1/admin/content/pages",
      "/api/v1/admin/content/pages/{id}",
      "/api/v1/admin/content/pages/{id}/archive",
      "/api/v1/admin/content/pages/{id}/publish",
      "/api/v1/admin/customers",
      "/api/v1/admin/customers/merge",
      "/api/v1/admin/customers/{id}",
      "/api/v1/admin/customers/{id}/addresses",
      "/api/v1/admin/customers/{id}/addresses/{addressId}",
      "/api/v1/admin/customers/{id}/addresses/{addressId}/default",
      "/api/v1/admin/customers/{id}/duplicates",
      "/api/v1/admin/customers/{id}/notes",
      "/api/v1/admin/customers/{id}/tags",
      "/api/v1/admin/inventory",
      "/api/v1/admin/inventory/adjustments",
      "/api/v1/admin/inventory/movements",
      "/api/v1/admin/inventory/reservations",
      "/api/v1/admin/inventory/reservations/expire",
      "/api/v1/admin/inventory/reservations/{reservationId}",
      "/api/v1/admin/inventory/reservations/{reservationId}/release",
      "/api/v1/admin/inventory/{variantId}",
      "/api/v1/admin/media",
      "/api/v1/admin/media/{id}",
      "/api/v1/admin/orders",
      "/api/v1/admin/orders/{id}",
      "/api/v1/admin/orders/{id}/address",
      "/api/v1/admin/orders/{id}/cancel",
      "/api/v1/admin/orders/{id}/contact",
      "/api/v1/admin/orders/{id}/notes",
      "/api/v1/admin/orders/{id}/payment",
      "/api/v1/admin/orders/{id}/return",
      "/api/v1/admin/orders/{id}/shipping",
      "/api/v1/admin/orders/{id}/status",
      "/api/v1/admin/products",
      "/api/v1/admin/products/{id}",
      "/api/v1/admin/products/{id}/archive",
      "/api/v1/admin/products/{id}/publish",
      "/api/v1/admin/products/{id}/variants",
      "/api/v1/admin/products/{productId}/variants/{variantId}",
      "/api/v1/admin/products/{productId}/variants/{variantId}/archive",
      "/api/v1/admin/promotions",
      "/api/v1/admin/promotions/{id}",
      "/api/v1/admin/promotions/{id}/archive",
      "/api/v1/admin/session",
      "/api/v1/cart",
      "/api/v1/cart/items",
      "/api/v1/cart/items/{lineId}",
      "/api/v1/cart/promotion",
      "/api/v1/catalog/categories",
      "/api/v1/catalog/categories/{slug}",
      "/api/v1/content/article-categories",
      "/api/v1/content/articles",
      "/api/v1/content/articles/{slug}",
      "/api/v1/content/home",
      "/api/v1/content/pages/{slug}",
      "/api/v1/favorites",
      "/api/v1/favorites/items",
      "/api/v1/favorites/items/{productId}",
      "/api/v1/orders",
      "/api/v1/orders/track",
      "/api/v1/products",
      "/api/v1/products/by-ids",
      "/api/v1/products/scope",
      "/api/v1/products/{slug}",
      "/api/v1/products/{slug}/related",
      "/api/v1/version",
      "/health/live",
      "/health/ready",
    ]);

    const operationIds = collectOperationIds(document);
    expect(operationIds.sort()).toEqual([
      "addAdminCustomerAddress",
      "addAdminCustomerNote",
      "addAdminOrderNote",
      "addCartItem",
      "addFavorite",
      "adminAdjustInventory",
      "adminArchiveArticle",
      "adminArchiveEditorialPage",
      "adminArchiveHomeContent",
      "adminArchiveProduct",
      "adminArchivePromotion",
      "adminArchiveVariant",
      "adminCreateArticle",
      "adminCreateAttribute",
      "adminCreateCategory",
      "adminCreateEditorialPage",
      "adminCreateInventoryReservation",
      "adminCreateMedia",
      "adminCreateProduct",
      "adminCreatePromotion",
      "adminCreateVariant",
      "adminDuplicateArticle",
      "adminExpireInventoryReservations",
      "adminGetArticle",
      "adminGetEditorialPage",
      "adminGetHomeContent",
      "adminGetInventoryReservation",
      "adminGetProduct",
      "adminGetPromotion",
      "adminListArticleCategories",
      "adminListArticles",
      "adminListAttributes",
      "adminListCategories",
      "adminListEditorialPages",
      "adminListInventory",
      "adminListMedia",
      "adminListProducts",
      "adminListPromotions",
      "adminListStockMovements",
      "adminPublishArticle",
      "adminPublishEditorialPage",
      "adminPublishHomeContent",
      "adminPublishProduct",
      "adminReleaseInventoryReservation",
      "adminUpdateArticle",
      "adminUpdateAttribute",
      "adminUpdateCategory",
      "adminUpdateEditorialPage",
      "adminUpdateHomeContent",
      "adminUpdateInventorySettings",
      "adminUpdateMedia",
      "adminUpdateProduct",
      "adminUpdatePromotion",
      "adminUpdateVariant",
      "applyCartPromotion",
      "cancelAdminOrder",
      "clearCart",
      "clearFavorites",
      "createGuestOrder",
      "deleteAdminCustomerAddress",
      "findAdminCustomerDuplicates",
      "getAdminCustomer",
      "getAdminOrder",
      "getAdminSession",
      "getCart",
      "getFavorites",
      "getLiveness",
      "getProductBySlug",
      "getPublicCatalogCategory",
      "getPublishedArticle",
      "getPublishedEditorialPage",
      "getPublishedHomeContent",
      "getReadiness",
      "getRelatedProducts",
      "getVersion",
      "listAdminCustomers",
      "listAdminOrders",
      "listArticleCategories",
      "listAuditEvents",
      "listCatalogScopeProducts",
      "listProducts",
      "listProductsByIds",
      "listPublicCatalogCategories",
      "listPublishedArticles",
      "mergeAdminCustomers",
      "removeCartItem",
      "removeCartPromotion",
      "removeFavorite",
      "returnAdminOrder",
      "setAdminCustomerDefaultAddress",
      "trackGuestOrder",
      "updateAdminCustomer",
      "updateAdminCustomerAddress",
      "updateAdminCustomerTags",
      "updateAdminOrderAddress",
      "updateAdminOrderContact",
      "updateAdminOrderPayment",
      "updateAdminOrderShipping",
      "updateAdminOrderStatus",
      "updateCartItem",
    ]);
    expect(new Set(operationIds).size).toBe(operationIds.length);
  }, 20_000);

  it("publishes reusable response and problem schemas", async () => {
    const document = await createOpenApiDocument();
    const schemas = document.components?.schemas;
    expect(schemas).toBeDefined();
    if (!schemas) throw new Error("OpenAPI components.schemas is required.");
    expect(Object.keys(schemas).sort()).toEqual([
      "AdminArticle",
      "AdminArticleList",
      "AdminAttribute",
      "AdminAttributeOption",
      "AdminAttributesResponse",
      "AdminCategoriesResponse",
      "AdminCategory",
      "AdminEditorialPage",
      "AdminEditorialPageBlock",
      "AdminEditorialPagesResponse",
      "AdminHomeContent",
      "AdminHomeDraftBody",
      "AdminInventoryResponse",
      "AdminInventoryRow",
      "AdminInventoryVariant",
      "AdminMediaAsset",
      "AdminMediaResponse",
      "AdminOrder",
      "AdminOrderCounters",
      "AdminOrderListResponse",
      "AdminProduct",
      "AdminProductMedia",
      "AdminProductVariant",
      "AdminProductsResponse",
      "AdminPromotion",
      "AdminPromotionsResponse",
      "AdminSession",
      "AdminStockMovement",
      "AdminStockMovementsResponse",
      "ArticleCategory",
      "AuditEvent",
      "AuditListResponse",
      "Cart",
      "CartLine",
      "Favorites",
      "HealthResponse",
      "Order",
      "OrderAddress",
      "OrderCustomer",
      "OrderItemSnapshot",
      "OrderTotals",
      "OrderTracking",
      "ProblemDetail",
      "Product",
      "PublicArticle",
      "PublicArticleList",
      "PublicArticleSummary",
      "PublicCategory",
      "PublicEditorialPage",
      "PublicHomeContent",
      "ReadinessResponse",
      "ReadinessUnavailableResponse",
      "ReservationExpiryResponse",
      "StockReservation",
      "VersionResponse",
    ]);
  }, 20_000);
});
