-- Phase 0 intentionally contains no business tables.
-- This migration anchors the reproducible migration chain; Phase 2 introduces
-- the private application schemas, grants, RLS policies, Auth profiles and audit log.
